---
  - hosts: all
    become: yes
    tasks:
      - name: Install python3
        apt:
          name: "{{ packages }}" 
          state: present 
          update_cache: yes
        vars:
          packages:
            - python3
            - python3-pip