---
  - hosts: all
    vars:
      dir: /srv/twitter
    become: yes
    tasks:
      - name: Git clone
        git: repo=https://github.com/I-himawari/TwSocialNetwork dest={{ dir }}

      - name: install
        pip:
          requirements: "{{ dir }}/requirements.txt"
          executable: pip3

      - name: copy api-key.yml
        copy:
          src: ../api-key.yml
          dest:  "{{ dir }}"